export const API_ENDPOINTS = {
  REQUEST_OTP: '/auth/vendor/request-otp',
  VERIFY_OTP: '/auth/vendor/verify-otp',
  VENDOR_ME: '/vendor/me',
  AVAILABILITY: '/vendor/me/availability',
  BANK: '/vendor/bank-accounts',
  ADDRESS: '/vendor/addresses',
  CITIES: '/cities',
  PRODUCT: '/products',
  PRODUCT_IMAGE: '/products/image',
  CATEGORIES: '/categories',
  VENDOR_ORDER: '/vendor/orders',
  DASHBOARD: '/vendor/dashboard',
  RIDERS: '/riders',
  EARNINGS: '/vendor/ledger/transactions',
};
